In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas/refs/heads/main/superstore_data.csv'

In [ ]:
dados_mercado = pd.read_csv(url)

In [ ]:
dados_mercado.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [ ]:
url_2 = 'https://raw.githubusercontent.com/alura-cursos/pandas/refs/heads/main/superstore_data_ponto_virgula.csv'

In [ ]:
dados_ponto_virgula = pd.read_csv(url_2)

In [ ]:
dados_ponto_virgula.head()

  Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

In [ ]:
dados_sem_virgula = pd.read_csv(url_2, sep=';')

In [ ]:
dados_sem_virgula.head()

In [ ]:
dados_primeiras_linhas = pd.read_csv(url, nrows=5)

In [ ]:
dados_primeiras_linhas

In [ ]:
dados_selecao = pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])

In [ ]:
dados_selecao

In [ ]:
dados_selecao = pd.read_csv(url, usecols=[0, 1, 4])

In [ ]:
dados_selecao

In [ ]:
dados_selecao.to_csv('clientes_mercado.csv')

In [ ]:
clientes_mercado = pd.read_csv('/content/clientes_mercado.csv')

In [ ]:
clientes_mercado

In [ ]:
dados_selecao.to_csv('dados_mercado.csv', index=False)

In [ ]:
pd.read_csv('/content/dados_mercado.csv')